spring:
  application:
    name: ${project.artifactId}
    version: ${project.version}
    namespace: ${banchile.system.namespace}

rabbitmq:
  concurrentConsumers: 5
  maxConcurrentConsumers: 5

server:
  port: 8666

logging:
  level:
    org.springframework: INFO
    cl.banchile: DEBUG

service:
  administra-ingreso-operaciones:
    scheme: http
    host: ${banchile.balisboot.host}
    port: 8162
    path: /ingreso-operaciones/v1/operaciones

canales:
  permitidos: PTV.BCO,MOV.MIN2,MOV.MIN,WEB.BCH,WEB.BCH2

operaciones:
  permitidas: DIVISA,FONDOSMUTUOS,ACCIONES